language: php

env:
  global:
    - COMPOSER_ROOT_VERSION="1.0.x-dev"

matrix:
  include:
    - php: 5.6
      env: DB=MYSQL PHPCS_TEST=1
    - php: 7.0
      env: DB=MYSQL
    - php: 7.1
      env: DB=MYSQL
    - php: 7.2
      env: DB=MYSQL

before_script:
  - phpenv rehash
  - phpenv config-rm xdebug.ini

  - composer validate
  - composer require silverstripe/recipe-core 1.0.x-dev  --no-update
  - composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

script:
  - vendor/bin/phpunit tests/
  - if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs src/ tests/ *.php; fi
